version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASS
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: django_ml
    environment:
      - DATABASE_URL
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  memcached:
    image: memcached:1-alpine
